MITRE: Changes to mapping from Command and Control
wazuh/wazuh-ruleset pull request #805
Opened 2020-12-02 21:54 UTC by mikykeane

This PR aims to tackle the issue from #803 

The following MITRE mappings have been changed:

- Rule ID: **5706**  `sshd: insecure connection attempt`  

> Removed
> **T1043** Deprecated. (**Commonly Used Port**). 
> 
> Added:
>  **T1021** **Remote Services**  -  **Lateral Movement**.
> 
> 

- Rule ID: **11209** `proftpd: Attempt to bypass firewall that can't adequately keep state of FTP traffic`

> Removed:  
> **T1043** Deprecated. (**Commonly Used Port**)  - **Command and Control**
> **T1065 Uncommonly Used Port**  - **Command and Control**

> Added: 
> **T1071**   **Application Layer Protocol**  - **Command and Control**
> 

- Rule ID: **11512** `Multiple FTP errors from the same source`

> Removed:
> **T1043** Deprecated. (**Commonly Used Port**)  - **Command and Control**
> 
> Added:
> **T1071**   **Application Layer Protocol**  - **Command and Control**
>  

- Rule ID: **82405** `Potential malware` 

> Removed:
> **T1043** Deprecated. (**Commonly Used Port**)  - **Command and Control**
> 
> Added:
> **T1071**  **Application Layer Protocol**  - **Command and Control**
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 

- Rule ID: **4325** `PIX: ARP collision detected`

> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 

- Rule ID: **7209** `Arpwatch: Possible arpspoofing attempt`

> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 

- Rule ID: **24061** `ARP cache:`

> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 
> 

- Rule ID: **64011** `ASA: ARP collision detected`

> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 
> 

The following are related to mapping of **T1102** **Web Service** - The concept is misunderstood. The technique refers to attacks done via Web services, NOT aimed at Web Services.

- Rule ID: **9510**  `Attack against Wordpress detected.`
- Rule ID: ** 30107** `Apache: Code Red attack.`
- Rule ID: ** 30307** `Apache: Client sent malformed Host header. Possible Code Red attack.`
- Rule ID: ** 31411** `PHP web attack.`

> Removed:
> **T1102** **Web Service**
> 

- Rule ID: **12101** `Invalid DNS packet. Possibility of attack.`

> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 
> 

- Rule ID: ** 81610**  `Fortigate: Default tunneling setting. Could be IPS.`

> Added:
> **T1572**  **Protocol Tunneling** - **Command and Control**
> 

- Rule ID: ** 81611** `Fortigate: Multiple default tunneling setting events from same source.`

> Removed:
> **T1071**   **Application Layer Protocol**  - **Command and Control**
> 
> Added:
> **T1572**  **Protocol Tunneling** - **Command and Control**
> 

- Rule ID: ** 82405** `Cisco eStreamer: APP-DETECT DNS request for potential malware`

> Removed:
> **T1043** Deprecated. (**Commonly Used Port**)  - **Command and Control**
> 
> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 

- Rule ID: ** 24215** `osquery: $(osquery.pack) $(osquery.subquery): MaMi malware detected, infected DNS address $(osquery.columns.address)`

> Added:
> **T1557**  **Man-in-the-Middle** -  **Credential Access**
> 

**NOTE**

The following mappings, have not yet been added to the framework: **T1557  Man-in-the-Middle** and   **T1572**  **Protocol Tunneling**

Therefore, they will not yet show in the dashboards until they are correctly added.

2021-07-02 13:20 UTC, fabamatic requested changes

2021-07-02 13:20 UTC, fabamatic commented on rules/0190-ms_ftpd_rules.xml
> +      <id>T1071</id>
T1071.002 "Application Layer Protocol: File Transfer Protocols" looks more accurate

2021-07-02 13:20 UTC, fabamatic commented on rules/0250-apache_rules.xml
>      <group>automatic_attack,pci_dss_6.2,pci_dss_6.5.2,pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SI.2,nist_800_53_SA.11,nist_800_53_SI.4,tsc_CC6.8,tsc_CC6.6,tsc_CC7.1,tsc_CC6.1,tsc_CC7.2,tsc_CC7.3,</gro
For this one the tags T1190 "Exploit Public-Facing Application" and T107.001 "Application Layer Protocol: Web Protocols" may be correct

2021-07-02 13:20 UTC, fabamatic commented on rules/0250-apache_rules.xml
>      <info type="text">CERT: Advisory CA-2001-19 "Code Red" Worm Exploiting Buffer Overflow In IIS Indexing Service DLL</info>
Same as above: For this one the tags T1190 "Exploit Public-Facing Application" and T107.001 "Application Layer Protocol: Web Protocols" may be correct

2021-07-02 13:20 UTC, fabamatic commented on rules/0265-php_rules.xml
>      <description>PHP web attack.</description>
Probably this one also pairs with  tags T1190 "Exploit Public-Facing Application" and T107.001 "Application Layer Protocol: Web Protocols"

2021-07-02 13:20 UTC, fabamatic commented on rules/0390-fortigate_rules.xml
>          <description>Fortigate: Multiple default tunneling setting events from same source.</description>
Not sure about this one: T1562.004 Impair Defenses: Disable or Modify System Firewall

2021-07-02 13:20 UTC, fabamatic commented on rules/0425-cisco-estreamer_rules.xml
> +            <id>T1071</id>
T1071.004 "Application Layer Protocol: DNS" is more accurate

2021-07-06 09:41 UTC, jcruzlp commented
These changes were added in this PR https://github.com/wazuh/wazuh/pull/9194

2021-07-06 09:41 UTC, closed without merging